### PR TITLE
Add boto dependency to be able to use EC2 module

### PR DESCRIPTION
**Pull request by brainstorm**
Hope that the pinning looks right, that version works for me. Thanks to @reisingerf and @LindsayHill.

### CODE REVIEW

**Review by arm4b — CHANGES_REQUESTED** [review]
Thanks for the contribution!

However for now, I'm not sure if this is good thing for a core Ansible pack.

Apart of `ec2` module there are many others with specific `pip` requirements:
- [consule](http://docs.ansible.com/ansible/latest/consul_module.html) module requires `python-consul`
- [selinux](http://docs.ansible.com/ansible/latest/selinux_module.html) module needs `libselinux-python`
- [junos](http://docs.ansible.com/ansible/latest/junos_banner_module.html) module needs `ncclient`
- [zabbix](http://docs.ansible.com/ansible/latest/zabbix_group_module.html) needs `zabbix-api` pip dependency

And so on from other Ansible modules http://docs.ansible.com/ansible/latest/list_of_all_modules.html, - you got the point.

This may change in future, but at the moment I don't think yet that we should allow all those requirements to be bundled in a pack, instead of providing clean raw Ansible functionality.

I would suggest just installing specific dependencies via `/opt/stackstorm/virtualenvs/ansible/bin/pip install boto` or using a fork.

This is somehow similar to [Ansible dependencies issues with st2 ansible pack #5](https://github.com/StackStorm-Exchange/stackstorm-ansible/issues/5) and [How to enforce a specific ansible version ? #4](https://github.com/StackStorm-Exchange/stackstorm-ansible/issues/4) issues which are still valid and unresolved.

**Comment by brainstorm** [comment]
Thanks @armab for the explanation. As much as I like the "batteries included" philosophy of Ansible, I get your point ;)

As a side note, though, there's a kerberos dependency in `requirements.txt` (pywinrm[credssp,kerberos]>=0.2.2) which is by no means "pure ansible" and which made my very first "st2 pack install ansible..." (inside the st2 docker container) fail out of the box earlier when I tried to install it.

I presume that this kerberos dependency is for your commercial RBAC?

/cc @reisingerf

**Comment by LindsayHill** [comment]
> I presume that this kerberos dependency is for your commercial RBAC?

No, it's something the Ansible seems to need for running actions against windows systems. Not connected to ST2 RBAC.

**Comment by brainstorm** [comment]
I proceeded [to fork and adjust `requirements.txt`](https://github.com/umccr/stackstorm-ansible), including the downgrade to ansible 2.2.x due to this bug, leaving it here for future reference:

https://github.com/ansible/ansible/issues/21562

**Pull request closed without merging**
